# Generated by Django 6.0.3 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_question_option_test_question_test_testresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
        ),
    ]
