# Generated by Django 6.0.3 on 2026-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_test_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("choice", "Выбор варианта"), ("text", "Развёрнутый ответ")],
                default="choice",
                max_length=10,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
