# Generated by Django 5.2.13 on 2026-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_answer_id_alter_comment_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы'),
        ),
    ]
