# Generated by Django 6.0.3 on 2026-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_answer_id_alter_comment_id_alter_option_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
        ),
    ]
